[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.7.0"
fumen = "0.1.2"
itertools = "0.14.0"
rayon = "1.10.0"
rustc-hash = "2.1.1"
smallvec = "1.15.1"

[[bench]]
name = "get_next"
harness = false
